import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import HeaderLeft from "../components/HeaderLeft";
import { ThemeProvider } from "../context/ThemeContext";

export const metadata: Metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "900"],
  variable: "--font-poppins",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
        <ThemeProvider>
          <div className="flex min-h-screen w-full subpixel-antialiased">
            <HeaderLeft />
            <main className="flex-[3]">{children}</main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
